[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.flit.metadata]
module = "fastapi_jwt_auth-latest"
dist-name = "fastapi-jwt-auth-latest"
author = ""
author-email = ["nyomanpradipta120@gmail.com", "internetwasmyidea@gmail.com"]
home-page = "https://github.com/IndominusByte/fastapi-jwt-auth"

classifiers = [
  "Environment :: Web Environment",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
  "Topic :: Software Development :: Libraries :: Python Modules"
]

requires = [
"fastapi>=0.85.1",
"PyJWT>=2.6.0"
]

description-file = "README.md"
requires-python = ">=3.8"

[tool.flit.metadata.urls]
Documentation = "https://indominusbyte.github.io/fastapi-jwt-auth/"

[tool.flit.metadata.requires-extra]
test = [
  "pytest==7.1.2",
  "pytest-cov==3.0.0",
  "coveralls==3.3.1"
]

doc = [
  "mkdocs==1.3.0",
  "mkdocs-material==8.3.7",
  "markdown-include==0.5.1,<0.6.0"
]

dev = [
  "cryptography==37.0.3",
  "uvicorn==0.17.6"
]

asymmetric = ["cryptography==37.0.3"]
